export const ROUTES = {
  SPLASH: 'Splash',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGOT_PASSWORD: 'ForgotPassword',
  PRE_ONBOARDING: 'PreOnboarding',
  APP_DRAWER: 'AppDrawer',
  HOME_TABS: 'HomeTabs',
  HOME: 'Home',
  CALENDAR: 'Calendar',
  QUICK_ACTIONS: 'QuickActions',
  CLIENTS: 'Clients',
  SHOP_TAB_ROOT: 'ShopTabRoot',
  SHOP_HOME: 'ShopHome',
  SHOP_CATEGORIES: 'ShopCategories',
  SHOP_FAVOURITES: 'ShopFavourites',
  SHOP_PRESCRIPTION: 'ShopPrescription',
  SHOP_SELLERS: 'ShopSellers',
  NOTIFICATIONS: 'Notifications',
  WALLET: 'Wallet',
  BUSINESS_ONBOARDING: 'BusinessOnboarding',
  PROFILE_SETTINGS: 'ProfileSettings',
  CART: 'Cart',
} as const;
